version: "3.5"
services:
  postgres:
    image: postgres:11
    #hostname: postgres
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: login-app
    ports:
      - '5432:5432'
  php-fpm:
    build:
      context: ./docker/php
    hostname: php-fpm
    volumes:
      - "./:/app"
    working_dir: "/app"
    expose:
      - 9000
    depends_on:
      - postgres
  nginx:
    image: nginx:latest
    hostname: nginx
    environment:
      WEB_DOCUMENT_ROOT: /app/public
      WEB_DOCUMENT_INDEX: index.php
      WEB_PHP_SOCKET: php-fpm:9000
    ports:
      - "8000:80"
    volumes:
      - "./:/app"
      - "./default.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      - php-fpm
  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    ports:
      - "8080:8080"